apiVersion: v1
kind: ConfigMap
metadata:
  name: kratos-config
data:
  kratos.yml: |
    dsn: memory
    dev: false
    serve:
      public:
        base_url: http://127.0.0.1:4433/
      admin:
        base_url: http://kratos-service:444/

    selfservice:
      default_browser_return_url: https://127.0.0.1:8080/
      allowed_return_urls:
        - http://127.0.0.1:8080/
      methods:
        password:
          enabled: true
      flows:
        error:
          ui_url: http://127.0.0.1/error
        settings:
          ui_url: http://127.0.0.1/settings
          privileged_session_max_age: 15m
        recovery:
          enabled: true
          ui_url: http://127.0.0.1/recovery
        verification:
          enabled: true
          ui_url: http://127.0.0.1/verification
          after:
            default_browser_return_url: http://127.0.0.1/
        logout:
          after:
            default_browser_return_url: http://127.0.0.1:8080/
        login:
          ui_url: http://127.0.0.1:8080/login
          lifespan: 10m
        registration:
          lifespan: 10m
          ui_url: http://127.0.0.1:8080/registration
          after:
            password:
              hooks:
                -
                  hook: session
    log:
      level: debug
      format: text
      leak_sensitive_values: false

    secrets:
      cookie:
        - PLEASE-CHANGE-ME-I-AM-VERY-INSECURE
      cipher:
        - 32-LONG-SECRET-NOT-SECURE-AT-ALL

    ciphers:
      algorithm: xchacha20-poly1305

    hashers:
      algorithm: bcrypt
      bcrypt:
        cost: 8

    identity:
      default_schema_id: default
      schemas:
        - id: default
          url: file:///etc/config/kratos/identity.schema.json
          
    courier:
      smtp:
        connection_uri: smtps://test:test@mailslurper:1025/?skip_ssl_verify=true