---
apiVersion: v1
kind: ConfigMap
metadata:
  name: yugabytedb-config
  labels:
    app: yugabytedb
data:
  YUGABYTE_DB: ory
  YUGABYTE_USER: yugabyte
  YUGABYTE_PASSWORD: yugabyte
---
apiVersion: v1
kind: Service
metadata:
  name: yugabytedb
  labels:
    app: yugabytedb
spec:
  type: LoadBalancer
  ports:
    - name: "tcp-ysql-port"
      port: 5433
    - name: "tcp-yedis-port"
      port: 6379
    - name: "http-ui1"
      port: 7000
    - name: "tcp-rpc-port1"
      port: 7100  
    - name: "http-ui2"
      port: 9000
    - name: "tcp-yql-port"
      port: 9042
    - name: "tcp-rpc-port2"
      port: 9100
    - name: "http-yedis-met"
      port: 11000
    - name: "http-ycql-met"
      port: 12000
    - name: "http-ysql-met"
      port: 13000

  selector:
   app: yugabytedb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yugabytedb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yugabytedb
  template:
    metadata:
      labels:
        app: yugabytedb
    spec:
      containers:
        - name: yugabytedb
          image: yugabytedb/yugabyte:2.17.0.0-b24
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5433
            - containerPort: 6379
            - containerPort: 7000
            - containerPort: 7100
            - containerPort: 9000
            - containerPort: 9100
            - containerPort: 9042
            - containerPort: 11000
            - containerPort: 12000
            - containerPort: 13000
          envFrom:
            - configMapRef:
                name: yugabytedb-config
          volumeMounts:
            - mountPath: /mnt/master
              name: yugabytedb
          command:
            - "/sbin/tini"
            - "--"
          args:
            - "/bin/bash"
            - "-c"
            - | 
              mkdir -p /var/ybinit
              echo CREATE DATABASE $${YUGABYTE_DB:-$${YUGABYTE_USER}} > /var/ybinit/01-db.sql
              echo create user $${YUGABYTE_USER} password '$${YUGABYTE_PASSWORD}' > /var/ybinit/02-usr.sql
              echo set log_statement='all'; set log_destination=stderr; > /var/ybinit/99-logging.sql
              /home/yugabyte/bin/yugabyted start --daemon=false --ui=true --initial_scripts_dir=/var/ybinit --tserver_flags=ysql_enable_auth=true
      volumes:
        - name: yugabytedb
          emptyDir: {}
