---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
data:
  POSTGRES_DB: ory
  POSTGRES_USER: oryadmin
  POSTGRES_PASSWORD: oryadminpwd
---
apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: postgres-config-data
  labels:
    app: postgres
data:
  create_tables.sql: |+
    CREATE DATABASE threeport_api;
    CREATE USER tp_rest_api WITH ENCRYPTED PASSWORD 'tp-rest-api-pwd';
    GRANT ALL PRIVILEGES ON DATABASE ory TO tp_rest_api;
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:9.6.24-alpine # https://github.com/ory/kratos/blob/acf92618559f59bc51ac28bf8251a4a1437f44cf/test/e2e/run.sh#L81
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
            - mountPath: /docker-entrypoint-initdb.d
              name: postgresql-initdb
      volumes:
        - name: postgredb
          emptyDir: {}
        - name: postgresql-initdb
          configMap:
            name: postgres-config-data
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  type: LoadBalancer
  ports:
   - port: 5432
  selector:
   app: postgres
